server:
  port: 8080
  # debug | release
  gin_mode: debug

log:
  level: debug
  logfile: ""
  show_fulltime: true
  report_caller: false

jwt:
  header_name: token
  # key to sign jwt
  key: SECRET_KEY
  exp: 24

mysql:
  enable: false
  orm: false
  # <user>[:password]@tcp(address)/<Database>[?parseTime=true][&loc=Local]
  # address format: host[:port] | /path/to/unix/socket/file
  dsn: <user>[:password]@tcp(localhost)/<Database>[?parseTime=true][&loc=Local]
  max_idle_conns: 0
  max_open_conns: 50

mongodb:
  enable: false
  url: mongodb://localhost:27017

tls:
  enable: false
  cert_file: cert.pem
  key_file: cert.key

cors:
  allow_origins:
    - "*"
  allow_methods:
    - GET
    - POST
  allow_headers:
    - Origin
    - Content-Length
    - Content-Type
  max_age: 43200

